- OCMS_WebAPI_Solution/OCMS_BOs/Helper/MappingHelper.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/SpecialtyModel.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/Repository/DepartmentRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/Repository/RoleRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/Repository/UserRepository.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/ISpecialtyService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/SpecialtyService.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/AuthorizeSettings/CustomAuthorizeAttribute.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/CandidateController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/DepartmentController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/LoginController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/SpecialtyController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/UserController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Program.cs
Import Candidate and CRUD Specialty version 2:
- Fix get CreatedAt and CreatedBy
- Fix get UpdatedAt and UpdatedBy
> Feat: Import Candidate and CRUD Specialty v2

- OCMS_WebAPI_Solution/OCMS_Services/Service/UserService.cs
Fix: get Name and create UserId and UserName logic
> Fix: Create Account function ver 2

- .github/workflows/main_ocms-vjvn.yml
Create Github Workflow for deploy ver1 (Maybe bugs - Need test)
> Feat: Create Github Workflow for deploy ver1

- OCMS_WebAPI_Solution/OCMS_BOs/Helper/MappingHelper.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/ExternalCertificateModel.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/GenericRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/IRepository/IExternalCertificateRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/Repository/ExternalCertificateRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/UnitOfWork.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/IBlobService.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/ICandidateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/IExternalCertificateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/AuthenticationService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/BlobService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/CandidateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/ExternalCertificateService.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/CandidateController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/DepartmentController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/ExternalCertificateController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/LoginController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Program.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/appsettings.Development.json
- OCMS_WebAPI_Solution/OCMS_WebAPI/appsettings.json
CRUD Candidate and External certificate
> Feat: CRUD Candidate and External certificate

- OCMS_WebAPI_Solution/OCMS_BOs/Helper/MappingHelper.cs
- OCMS_WebAPI_Solution/OCMS_BOs/RequestModel/ForgotPasswordDTO.cs
- OCMS_WebAPI_Solution/OCMS_BOs/RequestModel/PasswordUpdateDTO.cs
- OCMS_WebAPI_Solution/OCMS_BOs/RequestModel/ResetPasswordDTO.cs
- OCMS_WebAPI_Solution/OCMS_BOs/RequestModel/UserUpdateDTO.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/IUserService.cs
- OCMS_WebAPI_Solution/OCMS_Services/OCMS_Services.csproj
- OCMS_WebAPI_Solution/OCMS_Services/Service/UserService.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/UserController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Program.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/appsettings.Development.json
New features:
- Update User Details
- Update password
- Forgot password
- Reset password
- Using Redis to store ResetPasswordToken
> Feat: Update User Details and Password Functions

- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/UserModel.cs
Add: More details to User Model verson 1
> Add: More details to User Model v1

- OCMS_WebAPI_Solution/OCMS_BOs/Entities/Status.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Entities/TraineeAssign.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Helper/MappingHelper.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Migrations/20250329124546_adjustassignTable.Designer.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Migrations/20250329124546_adjustassignTable.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Migrations/20250329131835_adjustassignTablev2.Designer.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Migrations/20250329131835_adjustassignTablev2.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Migrations/20250329133724_adjustassignTablev3.Designer.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Migrations/20250329133724_adjustassignTablev3.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/TraineeAssignModel.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/IRepository/ITraineeAssignRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/Repository/TraineeAssignRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/UnitOfWork.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/ITraineeAssignService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/CandidateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/RequestService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/TraineeAssignService.cs
Traineeuser id is user with role "Trainee" 
[TraineeAssignImport.xlsx](https://github.com/user-attachments/files/19521478/TraineeAssignImport.xlsx)
> Add create and import trainee assign 

- OCMS_WebAPI_Solution/OCMS_BOs/Helper/MappingHelper.cs
- OCMS_WebAPI_Solution/OCMS_BOs/RequestModel/CreateSpecialtyDTO.cs
- OCMS_WebAPI_Solution/OCMS_BOs/RequestModel/UpdateSpecialtyDTO.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ResponseModel/CreateSpecialtyResponse.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ResponseModel/DeleteSpecialtyResponse.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ResponseModel/ErrorResponse.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ResponseModel/GetAllSpecialtiesResponse.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ResponseModel/GetSpecialtyResponse.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ResponseModel/GetSpecialtyTreeResponse.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ResponseModel/UpdateSpecialtyResponse.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/SpecialtyModel.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/SpecialtyTreeModel.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/IRepository/INotificationRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/Repository/NotificationRepository.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/ISpecialtyService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/SpecialtyService.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/SpecialtyController.cs
Modify: Change DTO for Specialty that will make the functions for Specialty clearly.
> Modify: Change DTO for Specialty

- OCMS_WebAPI_Solution/OCMS_BOs/Helper/MappingHelper.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/SpecialtyService.cs
Fix: Fix the Mapper and apply Mapper for SpecialtyService
> Fix: Fix the Mapper and apply Mapper for SpecialtyService

- OCMS_WebAPI_Solution/OCMS_BOs/Entities/Status.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Entities/TrainingSchedule.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Helper/MappingHelper.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Migrations/20250403115750_addfieldSchedule.Designer.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Migrations/20250403115750_addfieldSchedule.cs
- OCMS_WebAPI_Solution/OCMS_BOs/RequestModel/CourseDTO.cs
- OCMS_WebAPI_Solution/OCMS_BOs/RequestModel/TrainingScheduleDTO.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/TrainingScheduleModel.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/GenericRepository.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/CourseService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/InstructorAssignmentService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/RequestService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/TrainingScheduleService.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/CandidateController.cs
Validate schedule and update database, adjust course dto more understandable
> Schedule and Course adjust

- OCMS_WebAPI_Solution/OCMS_BOs/Entities/TraineeAssign.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Helper/MappingHelper.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Migrations/20250408063509_fixtraineeassigntable.Designer.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Migrations/20250408063509_fixtraineeassigntable.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/TraineeSubjectScheduleModel.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/TrainingScheduleModel.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/IRepository/ITrainingScheduleRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/Repository/TrainingScheduleRepository.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/IRequestService.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/ITrainingScheduleService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/RequestService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/TraineeAssignService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/TrainingScheduleService.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/RequestController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/TrainingScheduleController.cs
> Fix db and add trainee get schedule

- OCMS_WebAPI_Solution/OCMS_BOs/Helper/MappingHelper.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/SubjectModel.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/TrainingScheduleModel.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/IRepository/ICourseRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/IRepository/ITrainingPlanRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/Repository/CourseRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/Repository/TrainingPlanRepository.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/CourseService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/RequestService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/TrainingPlanService.cs
remove unnecessary null field in model
> Add detail for plan and course

- OCMS_WebAPI_Solution/OCMS_BOs/Entities/Status.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Helper/MappingHelper.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/UserModel.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/UserService.cs
Modify: Add RoleId and Name to UserModel
> Modify: Add RoleId and Name to UserModel

- OCMS_WebAPI_Solution/OCMS_BOs/Helper/MappingHelper.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/IRepository/IUserRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/Repository/UserRepository.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/UserService.cs
Fix: View RoleName in GetAllUser and GetUserById
> Fix: View RoleName in GetAllUser and GetUserById

- OCMS_WebAPI_Solution/OCMS_BOs/Entities/CourseParticipant.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Entities/Grade.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Entities/Status.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Helper/MappingHelper.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Migrations/20250409092748_newgradeDb.Designer.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Migrations/20250409092748_newgradeDb.cs
- OCMS_WebAPI_Solution/OCMS_BOs/RequestModel/GradeDTO.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/GradeModel.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/GenericRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/IRepository/IGradeRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/Repository/GradeRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/UnitOfWork.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/IGradeService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/GradeService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/SubjectService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/TraineeAssignService.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/GradeController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/TraineeAssignController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Program.cs
> Import grade

- OCMS_WebAPI_Solution/OCMS_BOs/Helper/MappingHelper.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/ICertificateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/CandidateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/CertificateService.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/CertificateController.cs
Features:
- Create Certificate for 1 Trainee
- View Trainee Certificates
- Delete Certificate
> Feat: Create Certificate function

- OCMS_WebAPI_Solution/OCMS_BOs/ResponseModel/CreateCertificateTemplateResponse.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ResponseModel/GetCertificateTemplateResponse.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ResponseModel/ImportResult.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/ExternalCertificateModel.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/UserModel.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/IRepository/IGradeRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/IRepository/ITraineeAssignRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/IRepository/IUserRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/Repository/GradeRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/Repository/TraineeAssignRepository.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/Repository/UserRepository.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/IBlobService.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/ICertificateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/BlobService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/CandidateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/CertificateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/CertificateTemplateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/ExternalCertificateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/GradeService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/UserService.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/CertificateController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Program.cs
Feature: 
- View Blob data with SAS token
- Auto Generate Certificate
> Feat: View Blob data with SAS token and Auto Generate Certificate

- OCMS_WebAPI_Solution/OCMS_Services/Service/PdfSignerService.cs
> Fix: Sign Certificate v2

- OCMS_WebAPI_Solution/OCMS_BOs/OCMS_BOs.csproj
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/CertificateModel.cs
- OCMS_WebAPI_Solution/OCMS_Repositories/Repository/CertificateRepository.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/ICertificateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/BlobService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/CertificateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/PdfSignerService.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/.config/dotnet-tools.json
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/CertificateController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/UserController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/OCMS_WebAPI.csproj
- OCMS_WebAPI_Solution/OCMS_WebAPI/appsettings.Development.json
Get Pending/Active Certificate, Get Certificate by user/certificate Id
> Feat: Get Pending/Active Certificate, Get Certificate by user/certificate Id

- OCMS_WebAPI_Solution/OCMS_BOs/Helper/MappingHelper.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/DecisionModel.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/IDecisionService.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/IPdfSignerService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/CertificateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/CourseService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/DecisionService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/GradeService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/InstructorAssignmentService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/PdfSignerService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/SubjectService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/TraineeAssignService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/TrainingPlanService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/TrainingScheduleService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/UserService.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/DecisonController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/PdfSignController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/UserController.cs
Feat: Sign Decision and CRD Decision
> Feat: Sign Decision and CRD Decision

- OCMS_WebAPI_Solution/OCMS_BOs/Entities/Course.cs
- OCMS_WebAPI_Solution/OCMS_BOs/Entities/Status.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/ICertificateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/IProgressTrackingService.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/IUserService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Middleware/StatusCheckBackgroundService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/CertificateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/CertificateTemplateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/DecisionService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/GradeService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/ProgressTrackingService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/RequestService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/UserService.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/CertificateController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/CourseController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/DepartmentController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/GradeController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/InstructorAssignmentController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/NotificationController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/PdfSignController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/ReportController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/RequestController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/SpecialtyController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/SubjectController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/TraineeAssignController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/TrainingScheduleController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/UserController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Program.cs
Add Progress Tracking for Subject, Course and TrainingPlan
Add Background Service to check if EndDate and StartDate
> Feat: Progress Tracking and Background Service

- OCMS_WebAPI_Solution/OCMS_Services/Service/CertificateMonitoringService.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/CertificateController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/DepartmentController.cs
Fix: Add Role to Get User Certificate and Add check Notification for expire Certificate
> Fix: Add Role to Get User Certificate and Add check Notification for expire Certificate

- OCMS_WebAPI_Solution/OCMS_BOs/Entities/Status.cs
- OCMS_WebAPI_Solution/OCMS_BOs/ViewModel/TraineViewModel.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/IGradeService.cs
- OCMS_WebAPI_Solution/OCMS_Services/IService/ISubjectService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/CertificateService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/GradeService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/RequestService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/SubjectService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/TraineeAssignService.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/CertificateController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/GradeController.cs
- OCMS_WebAPI_Solution/OCMS_WebAPI/Controllers/SubjectController.cs
update grade, renew certificate, view trainee by subject id
> add revoke request

- OCMS_WebAPI_Solution/OCMS_Services/Service/GradeService.cs
- OCMS_WebAPI_Solution/OCMS_Services/Service/TrainingScheduleService.cs
Fix grade and decision and validate schedule
> Fix Common
